import { useState } from "react";
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { SafeAreaView, useSafeAreaInsets } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { useLocalSearchParams, useRouter } from "expo-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import * as Haptics from "expo-haptics";

import { mobileClient } from "../../src/api/mobileClient";
import { useCall } from "../../src/context/CallContext";
import { colors } from "../../src/theme/tokens";

export default function ChatScreen() {
  const router = useRouter(); const client = useQueryClient(); const insets = useSafeAreaInsets(); const { id, role } = useLocalSearchParams<{ id: string; role?: "student" | "guide" }>(); const conversationId = Number(id); const activeRole = role === "guide" ? "guide" : "student"; const { startCall, isStarting } = useCall(); const [body, setBody] = useState(""); const [sending, setSending] = useState(false);
  const { data, isLoading, refetch } = useQuery({ queryKey: ["conversation", conversationId], queryFn: () => mobileClient.getConversation(conversationId), enabled: Number.isFinite(conversationId), refetchInterval: 12_000 });
  const { data: bookings = [] } = useQuery({ queryKey: ["call-bookings", activeRole], queryFn: () => mobileClient.getCallBookings(activeRole), staleTime: 30_000 });
  const booking = bookings.find((item) => item.peerId === data?.conversation.peerId && item.bookingStatus === "accepted");
  async function send() { const text = body.trim(); if (!text || sending) return; setSending(true); setBody(""); try { await mobileClient.sendConversationMessage(conversationId, text); await Promise.all([refetch(), client.invalidateQueries({ queryKey: ["conversations"] })]); } finally { setSending(false); } }
  return <View style={s.root}><SafeAreaView edges={["top"]} style={s.safe}><View style={s.header}><Pressable onPress={() => router.back()} hitSlop={12} style={s.back}><Ionicons name="chevron-back" size={21} color={colors.ink} /></Pressable><View style={s.headerCopy}><Text style={s.name} numberOfLines={1}>{data?.conversation.displayName ?? "Guide"}</Text><Text style={s.sub} numberOfLines={1}>{data?.conversation.universityName ?? ""}</Text></View>{booking ? <Pressable onPress={() => { Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Medium); startCall(booking.bookingId, booking.fullName, booking.universityName); }} disabled={isStarting} style={s.call}><Ionicons name="call" size={18} color="#fff" /></Pressable> : <View style={s.callDisabled}><Ionicons name="call-outline" size={18} color={colors.faint} /></View>}</View></SafeAreaView><KeyboardAvoidingView style={s.flex} behavior={Platform.OS === "ios" ? "padding" : "height"}>{isLoading ? <View style={s.center}><ActivityIndicator color={colors.primary} /></View> : <><ScrollView contentContainerStyle={s.messages}>{data?.messages.map((message) => <View key={message.id} style={[s.bubble, message.isMine ? s.mine : s.theirs]}><Text style={[s.bubbleText, message.isMine && s.mineText]}>{message.body}</Text></View>)}</ScrollView><View style={[s.composer, { paddingBottom: Math.max(insets.bottom, 10) }]}><TextInput value={body} onChangeText={setBody} placeholder="Message" placeholderTextColor={colors.faint} style={s.input} multiline /><Pressable onPress={send} disabled={!body.trim() || sending} style={[s.send, (!body.trim() || sending) && s.sendDisabled]}>{sending ? <ActivityIndicator size="small" color="#fff" /> : <Ionicons name="send" size={18} color="#fff" />}</Pressable></View></>}</KeyboardAvoidingView></View>;
}
const s = StyleSheet.create({ root: { flex: 1, backgroundColor: "#EEF4F0" }, flex: { flex: 1 }, safe: { backgroundColor: colors.surface, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.line }, header: { height: 58, paddingHorizontal: 16, flexDirection: "row", alignItems: "center", gap: 12 }, back: { width: 36, height: 36, borderRadius: 18, alignItems: "center", justifyContent: "center", backgroundColor: colors.primarySoft }, headerCopy: { flex: 1, minWidth: 0 }, name: { fontFamily: "PlusJakartaSans-Bold", fontSize: 14, color: colors.ink }, sub: { fontFamily: "PlusJakartaSans-Regular", fontSize: 11, color: colors.muted, marginTop: 2 }, call: { width: 38, height: 38, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: colors.primary }, callDisabled: { width: 38, height: 38, borderRadius: 13, alignItems: "center", justifyContent: "center", backgroundColor: colors.primarySoft }, center: { flex: 1, alignItems: "center", justifyContent: "center" }, messages: { paddingHorizontal: 16, paddingVertical: 18, gap: 8 }, bubble: { maxWidth: "82%", paddingHorizontal: 13, paddingVertical: 10, borderRadius: 16 }, mine: { alignSelf: "flex-end", backgroundColor: colors.primary, borderBottomRightRadius: 4 }, theirs: { alignSelf: "flex-start", backgroundColor: colors.surface, borderBottomLeftRadius: 4 }, bubbleText: { fontFamily: "PlusJakartaSans-Regular", fontSize: 14, lineHeight: 20, color: colors.ink }, mineText: { color: "#fff" }, composer: { flexDirection: "row", alignItems: "flex-end", gap: 9, paddingHorizontal: 12, paddingTop: 10, backgroundColor: colors.surface, borderTopWidth: StyleSheet.hairlineWidth, borderTopColor: colors.line }, input: { flex: 1, minHeight: 44, maxHeight: 108, borderRadius: 18, backgroundColor: "#F2F5F3", fontFamily: "PlusJakartaSans-Regular", fontSize: 14, color: colors.ink, paddingHorizontal: 14, paddingVertical: 11, textAlignVertical: "center" }, send: { width: 44, height: 44, borderRadius: 16, alignItems: "center", justifyContent: "center", backgroundColor: colors.primary }, sendDisabled: { opacity: 0.42 } });
