import { getCountryHeroImage } from "@/lib/country-media";

export type LocationMedia = {
  url: string;
  alt: string;
  sourceLabel?: string;
  sourceUrl?: string;
};

const cityMediaMap: Record<string, LocationMedia> = {
  "georgia::tbilisi": {
    url: "https://images.pexels.com/photos/32565386/pexels-photo-32565386.jpeg?cs=srgb&dl=pexels-eslames1-32565386.jpg&fm=jpg",
    alt: "Aerial skyline view of Tbilisi, Georgia",
    sourceLabel: "Pexels",
    sourceUrl: "https://www.pexels.com/photo/breathtaking-aerial-view-of-tbilisi-skyline-32565386/",
  },
  "vietnam::hanoi": {
    url: "https://images.pexels.com/photos/5909334/pexels-photo-5909334.jpeg?cs=srgb&dl=pexels-nguy-n-ph-ng-linh-3931723-5909334.jpg&fm=jpg",
    alt: "Skyline view of Hanoi, Vietnam",
    sourceLabel: "Pexels",
    sourceUrl: "https://www.pexels.com/photo/city-skyline-under-white-sky-5909334/",
  },
  "vietnam::ho chi minh city": {
    url: "https://images.pexels.com/photos/32196732/pexels-photo-32196732.jpeg?cs=srgb&dl=pexels-huu-duy-foto-685214803-32196732.jpg&fm=jpg",
    alt: "Panoramic skyline of Ho Chi Minh City, Vietnam",
    sourceLabel: "Pexels",
    sourceUrl: "https://www.pexels.com/photo/skyline-view-of-ho-chi-minh-city-skyline-32196732/",
  },
  "vietnam::da nang": {
    url: "https://images.pexels.com/photos/12162281/pexels-photo-12162281.jpeg?cs=srgb&dl=pexels-anh-huynh-tuan-673356-12162281.jpg&fm=jpg",
    alt: "Da Nang skyline with the Han River and Dragon Bridge",
    sourceLabel: "Pexels",
    sourceUrl: "https://www.pexels.com/photo/city-skyline-across-body-of-water-12162281/",
  },
  "albania::tirana": {
    url: "/images/countries/albania.jpg",
    alt: "Skanderbeg Square, Tirana, Albania",
    sourceLabel: "Wikimedia Commons",
  },
  "lithuania::kaunas": {
    url: "/images/cities/kaunas.jpg",
    alt: "Town Hall Square (Rotušės aikštė), Kaunas, Lithuania",
    sourceLabel: "Wikimedia Commons",
  },
  "lithuania::vilnius": {
    url: "/images/countries/lithuania.jpg",
    alt: "Vilnius Old Town skyline and cathedral, Lithuania",
    sourceLabel: "Wikimedia Commons",
  },
  "australia::brisbane": {
    url: "https://upload.wikimedia.org/wikipedia/commons/c/ca/Skyline_of_Brisbane_from_Kangaroo_Point_Cliffs_Park%2C_Nov_2020%2C_05.jpg",
    alt: "Brisbane skyline viewed from Kangaroo Point Cliffs Park",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Skyline_of_Brisbane_from_Kangaroo_Point_Cliffs_Park,_Nov_2020,_05.jpg",
  },
  "australia::canberra": {
    url: "https://upload.wikimedia.org/wikipedia/commons/f/f4/Canberra_skyline%2C_York_Park_conservation_site%2C_The_National_Circuit%2C_Barton%2C_ACT_IMGP9718.jpg",
    alt: "Canberra skyline seen from York Park, Barton",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Canberra_skyline,_York_Park_conservation_site,_The_National_Circuit,_Barton,_ACT_IMGP9718.jpg",
  },
  "australia::newcastle": {
    url: "https://upload.wikimedia.org/wikipedia/commons/2/2c/Newcastle_from_Fort_Scratchley.jpg",
    alt: "Newcastle, New South Wales, viewed from Fort Scratchley",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Newcastle_from_Fort_Scratchley.jpg",
  },
  "australia::sydney": {
    url: "https://upload.wikimedia.org/wikipedia/commons/8/81/Sydney_Opera_House_and_Harbour_Bridge_Dusk_2019-06-21.jpg",
    alt: "Sydney Opera House and Harbour Bridge at dusk",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sydney_Opera_House_and_Harbour_Bridge_Dusk_2019-06-21.jpg",
  },
  "australia::townsville": {
    url: "https://upload.wikimedia.org/wikipedia/commons/9/97/Townsville_from_castle_hill_lookout_near_sunset.jpg",
    alt: "Townsville skyline viewed from Castle Hill lookout near sunset",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Townsville_from_castle_hill_lookout_near_sunset.jpg",
  },
  "bosnia-and-herzegovina::mostar": {
    url: "https://upload.wikimedia.org/wikipedia/commons/d/d7/Mostar_Old_Town_Panorama_2007.jpg",
    alt: "Mostar Old Town panorama with the Stari Most bridge over the Neretva River",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Mostar_Old_Town_Panorama_2007.jpg",
  },
  "bosnia-and-herzegovina::sarajevo": {
    url: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Sarajevo_City_Panorama.JPG",
    alt: "Panoramic view of Sarajevo city",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Sarajevo_City_Panorama.JPG",
  },
  "british-virgin-islands::tortola": {
    url: "https://upload.wikimedia.org/wikipedia/commons/3/3b/Road_Town%2C_Tortola%2C_British_Virgin_Islands_%2832711582262%29.jpg",
    alt: "Road Town, the capital of Tortola, British Virgin Islands",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Road_Town,_Tortola,_British_Virgin_Islands_(32711582262).jpg",
  },
  "canada::barrie": {
    url: "https://upload.wikimedia.org/wikipedia/commons/e/ea/Barrie_skyline_2025.jpg",
    alt: "Barrie, Ontario skyline",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Barrie_skyline_2025.jpg",
  },
  "canada::calgary": {
    url: "https://upload.wikimedia.org/wikipedia/commons/a/af/Calgary_2023.jpg",
    alt: "Calgary downtown skyline",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Calgary_2023.jpg",
  },
  "canada::edmonton": {
    url: "https://upload.wikimedia.org/wikipedia/commons/f/fc/Edmonton_Skyline_2020.jpg",
    alt: "Edmonton downtown skyline",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Edmonton_Skyline_2020.jpg",
  },
  "canada::kingston": {
    url: "https://upload.wikimedia.org/wikipedia/commons/c/ce/Kingston_Harbour_from_Fort_Henry_-_panoramio.jpg",
    alt: "Kingston, Ontario harbour viewed from Fort Henry",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Kingston_Harbour_from_Fort_Henry_-_panoramio.jpg",
  },
  "canada::new westminster": {
    url: "https://upload.wikimedia.org/wikipedia/commons/7/78/View_of_City_of_New_Westminster_in_November_2024.jpg",
    alt: "View of New Westminster, British Columbia skyline",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:View_of_City_of_New_Westminster_in_November_2024.jpg",
  },
  "czech-republic::ostrava": {
    url: "https://upload.wikimedia.org/wikipedia/commons/0/0b/Pohled_na_Ostravu_z_Nov%C3%A9_radnice%2C_srpen_2011%2C_4.jpg",
    alt: "View of Ostrava from the New City Hall tower",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Pohled_na_Ostravu_z_Nov%C3%A9_radnice,_srpen_2011,_4.jpg",
  },
  "france::fontainebleau": {
    url: "https://upload.wikimedia.org/wikipedia/commons/8/85/Le_Grand_Escalier_%C3%A0_Fer_de_Cheval.jpg",
    alt: "The Horseshoe Staircase (Escalier en Fer-a-Cheval) at the Chateau de Fontainebleau",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Le_Grand_Escalier_%C3%A0_Fer_de_Cheval.jpg",
  },
  "france::lille": {
    url: "https://upload.wikimedia.org/wikipedia/commons/2/2b/Grand_place%2C_Lille.jpg",
    alt: "Grand Place (Place du General de Gaulle) in Lille, France, with the Vieille Bourse",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Grand_place,_Lille.jpg",
  },
  "france::paris": {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Eiffel_Tower_and_Pont_Alexandre_III_at_night.jpg/1280px-Eiffel_Tower_and_Pont_Alexandre_III_at_night.jpg",
    alt: "Eiffel Tower and Pont Alexandre III at night, Paris",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Eiffel_Tower_and_Pont_Alexandre_III_at_night.jpg",
  },
  "georgia::gori": {
    url: "https://upload.wikimedia.org/wikipedia/commons/1/19/View_of_Gori_from_Gori_Fortress_%28photo_by_Peterfitzgerald%2C_2005%29.JPEG",
    alt: "View of Gori, Georgia, from Gori Fortress",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:View_of_Gori_from_Gori_Fortress_(photo_by_Peterfitzgerald,_2005).JPEG",
  },
  "georgia::kutaisi": {
    url: "https://upload.wikimedia.org/wikipedia/commons/4/40/Downtown_Kutaisi_%26_White_Bridge_as_seen_from_Mt_Gora_%28August_2011%29-cropped.jpg",
    alt: "Downtown Kutaisi and the White Bridge, Georgia, seen from Mount Gora",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Downtown_Kutaisi_%26_White_Bridge_as_seen_from_Mt_Gora_(August_2011)-cropped.jpg",
  },
  "germany::frankfurt": {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Skyline_Frankfurt_am_Main_2015.jpg/1280px-Skyline_Frankfurt_am_Main_2015.jpg",
    alt: "Frankfurt am Main skyline",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Skyline_Frankfurt_am_Main_2015.jpg",
  },
  "germany::hamburg": {
    url: "https://upload.wikimedia.org/wikipedia/commons/e/e3/Hamburg_city_skyline.jpg",
    alt: "Hamburg city skyline seen from the Aussenalster",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Hamburg_city_skyline.jpg",
  },
  "hungary::debrecen": {
    url: "https://upload.wikimedia.org/wikipedia/commons/5/52/Great_Protestant_Church_of_Debrecen_3564.jpg",
    alt: "The Great Protestant Church (Nagytemplom) in Debrecen, Hungary",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Great_Protestant_Church_of_Debrecen_3564.jpg",
  },
  "ireland::galway": {
    url: "https://upload.wikimedia.org/wikipedia/commons/e/e6/Spanish_Arch_%26_The_Long_Walk_-_Galway.jpg",
    alt: "Spanish Arch and the Long Walk in Galway, Ireland",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Spanish_Arch_%26_The_Long_Walk_-_Galway.jpg",
  },
  "italy::rome": {
    url: "https://upload.wikimedia.org/wikipedia/commons/5/53/Colosseum_in_Rome%2C_Italy_-_April_2007.jpg",
    alt: "The Colosseum in Rome, Italy",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Colosseum_in_Rome,_Italy_-_April_2007.jpg",
  },
  "kazakhstan::almaty": {
    url: "https://upload.wikimedia.org/wikipedia/commons/8/8c/Almaty_city_skyline.jpg",
    alt: "Skyline of Almaty, Kazakhstan",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Almaty_city_skyline.jpg",
  },
  "kyrgyzstan::bishkek": {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/%D0%91%D0%B8%D1%88%D0%BA%D0%B5%D0%BA_%283-%D0%BC%D0%B0%D1%80%D1%82_2025%29.jpg/1280px-%D0%91%D0%B8%D1%88%D0%BA%D0%B5%D0%BA_%283-%D0%BC%D0%B0%D1%80%D1%82_2025%29.jpg",
    alt: "Cityscape of Bishkek, Kyrgyzstan",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:%D0%91%D0%B8%D1%88%D0%BA%D0%B5%D0%BA_(3-%D0%BC%D0%B0%D1%80%D1%82_2025).jpg",
  },
  "kyrgyzstan::jalal-abad": {
    url: "https://upload.wikimedia.org/wikipedia/commons/2/26/Jalalabad_sity.jpg",
    alt: "Hillside city sign overlooking Jalal-Abad (Manas), Kyrgyzstan",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Jalalabad_sity.jpg",
  },
  "kyrgyzstan::kant": {
    url: "https://upload.wikimedia.org/wikipedia/commons/7/70/%D0%9A%D0%B0%D0%BD%D1%82_%D1%81%D0%B2%D0%B5%D1%80%D1%85%D1%83.jpg",
    alt: "Aerial view of Kant, Kyrgyzstan",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:%D0%9A%D0%B0%D0%BD%D1%82_%D1%81%D0%B2%D0%B5%D1%80%D1%85%D1%83.jpg",
  },
  "kyrgyzstan::osh": {
    url: "https://upload.wikimedia.org/wikipedia/commons/e/e8/Osh%2C_Kyrgyzstan_-_panoramio.jpg",
    alt: "View of Osh, Kyrgyzstan with surrounding mountains",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Osh,_Kyrgyzstan_-_panoramio.jpg",
  },
  "latvia::riga": {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/House_of_Blackheads_and_St._Peter%27s_Church_Tower%2C_Riga%2C_Latvia_-_Diliff.jpg/1280px-House_of_Blackheads_and_St._Peter%27s_Church_Tower%2C_Riga%2C_Latvia_-_Diliff.jpg",
    alt: "House of Blackheads and St. Peter's Church Tower, Riga, Latvia",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:House_of_Blackheads_and_St._Peter%27s_Church_Tower,_Riga,_Latvia_-_Diliff.jpg",
  },
  "lithuania::utena": {
    url: "https://upload.wikimedia.org/wikipedia/commons/1/18/Utena_city_-_Real_is_beautiful.jpg",
    alt: "Aerial view of Utena, Lithuania",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Utena_city_-_Real_is_beautiful.jpg",
  },
  "macau::macau": {
    url: "https://upload.wikimedia.org/wikipedia/commons/0/02/Panorama_of_Macau_Peninsula2021.jpg",
    alt: "Panorama of the Macau Peninsula skyline",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Panorama_of_Macau_Peninsula2021.jpg",
  },
  "malta::floriana": {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Malta_-_Floriana_-_W._Bonnici_-_Marsamxett_Harbour.jpg/1280px-Malta_-_Floriana_-_W._Bonnici_-_Marsamxett_Harbour.jpg",
    alt: "Marsamxett Harbour view from Floriana, Malta",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Malta_-_Floriana_-_W._Bonnici_-_Marsamxett_Harbour.jpg",
  },
  "malta::kalkara": {
    url: "https://upload.wikimedia.org/wikipedia/commons/b/b8/Kalkara_as_seen_from_Valletta.jpg",
    alt: "Kalkara waterfront as seen from Valletta, Malta",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Kalkara_as_seen_from_Valletta.jpg",
  },
  "netherlands::utrecht": {
    url: "https://upload.wikimedia.org/wikipedia/commons/9/9e/Panorama_of_Utrecht.jpeg",
    alt: "Panoramic skyline of Utrecht, Netherlands",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Panorama_of_Utrecht.jpeg",
  },
  "new-zealand::auckland": {
    url: "https://upload.wikimedia.org/wikipedia/commons/7/7c/Aerial_view_of_Auckland.jpg",
    alt: "Aerial view of Auckland, New Zealand",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Aerial_view_of_Auckland.jpg",
  },
  "new-zealand::wellington": {
    url: "https://upload.wikimedia.org/wikipedia/commons/6/6f/Wellington_City_seen_from_Mount_Victoria_%28165463611%29.jpg",
    alt: "Wellington city skyline seen from Mount Victoria, New Zealand",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Wellington_City_seen_from_Mount_Victoria_(165463611).jpg",
  },
  "north-macedonia::skopje": {
    url: "https://upload.wikimedia.org/wikipedia/commons/0/0e/Stone_Bridge_Skopje_4.jpg",
    alt: "Macedonia Square seen from the Stone Bridge, Skopje",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Stone_Bridge_Skopje_4.jpg",
  },
  "north-macedonia::stip": {
    url: "https://upload.wikimedia.org/wikipedia/commons/3/39/Stip_Macedonia_-_Panorama_from_Isar_Hill_1.jpg",
    alt: "Panorama of Stip, North Macedonia from Isar Hill",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Stip_Macedonia_-_Panorama_from_Isar_Hill_1.jpg",
  },
  "norway::bergen": {
    url: "https://upload.wikimedia.org/wikipedia/commons/8/86/Bergen_from_Mount_Floyen.jpg",
    alt: "View of Bergen, Norway from Mount Floyen",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Bergen_from_Mount_Floyen.jpg",
  },
  "philippines::angeles city": {
    url: "https://upload.wikimedia.org/wikipedia/commons/0/09/Angeles_City_2021.jpg",
    alt: "Aerial cityscape of Angeles City, Philippines",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Angeles_City_2021.jpg",
  },
  "portugal::sintra": {
    url: "https://upload.wikimedia.org/wikipedia/commons/d/d6/View_overlooking_the_rooftops_of_Sintra%2C_Portugal_%2855155502333%29.jpg",
    alt: "View overlooking the rooftops of Sintra, Portugal",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:View_overlooking_the_rooftops_of_Sintra,_Portugal_(55155502333).jpg",
  },
  "russia::abakan": {
    url: "https://upload.wikimedia.org/wikipedia/commons/8/87/2012-07-24_%D0%B2%D0%B8%D0%B4_%D0%B8%D0%B7_%D1%81%D0%B0%D0%BC%D0%BE%D0%BB%D1%91%D1%82%D0%B0_%D0%BD%D0%B0_%D0%B3%D0%BE%D1%80%D0%BE%D0%B4_%D0%90%D0%B1%D0%B0%D0%BA%D0%B0%D0%BD.jpg",
    alt: "Aerial view of Abakan, Russia from an airplane",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:2012-07-24_%D0%B2%D0%B8%D0%B4_%D0%B8%D0%B7_%D1%81%D0%B0%D0%BC%D0%BE%D0%BB%D1%91%D1%82%D0%B0_%D0%BD%D0%B0_%D0%B3%D0%BE%D1%80%D0%BE%D0%B4_%D0%90%D0%B1%D0%B0%D0%BA%D0%B0%D0%BD.jpg",
  },
  "russia::barnaul": {
    url: "https://upload.wikimedia.org/wikipedia/commons/a/a5/%D0%92%D0%B8%D0%B4_%D0%BD%D0%B0_%D0%91%D0%B0%D1%80%D0%BD%D0%B0%D1%83%D0%BB_%D1%81_%D0%B3%D0%BE%D1%80%D1%8B_%2840064543275%29.jpg",
    alt: "View of Barnaul, Russia from a hill",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:%D0%92%D0%B8%D0%B4_%D0%BD%D0%B0_%D0%91%D0%B0%D1%80%D0%BD%D0%B0%D1%83%D0%BB_%D1%81_%D0%B3%D0%BE%D1%80%D1%8B_(40064543275).jpg",
  },
  "russia::blagoveshchensk": {
    url: "https://upload.wikimedia.org/wikipedia/commons/1/1f/Blagoveshchensk%2C_Russia_%2812756226795%29.jpg",
    alt: "Cityscape of Blagoveshchensk, Russia",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Blagoveshchensk,_Russia_(12756226795).jpg",
  },
  "russia::cheboksary": {
    url: "https://upload.wikimedia.org/wikipedia/commons/4/4d/Cheboksary._View_of_downtown.jpg",
    alt: "View of downtown Cheboksary, Russia",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Cheboksary._View_of_downtown.jpg",
  },
  "russia::chelyabinsk": {
    url: "https://upload.wikimedia.org/wikipedia/commons/b/bb/Tsentralnyy_rayon%2C_Chelyabinsk%2C_Chelyabinskaya_oblast%27%2C_Russia_-_panoramio_%281%29.jpg",
    alt: "Panorama of central Chelyabinsk, Russia",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Tsentralnyy_rayon,_Chelyabinsk,_Chelyabinskaya_oblast',_Russia_-_panoramio_(1).jpg",
  },
  "russia::cherkessk": {
    url: "https://upload.wikimedia.org/wikipedia/commons/9/96/Cherkessk%2C_Karachay-Cherkessia%2C_Russia_-_panoramio_%282%29.jpg",
    alt: "Panoramic cityscape of Cherkessk, Russia",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Cherkessk,_Karachay-Cherkessia,_Russia_-_panoramio_(2).jpg",
  },
  "russia::grozny": {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Grozny_panorama.jpg/1280px-Grozny_panorama.jpg",
    alt: "Panorama of Grozny, Russia",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Grozny_panorama.jpg",
  },
  "russia::irkutsk": {
    url: "https://upload.wikimedia.org/wikipedia/commons/1/13/Teatr_Dramatyczny_w_Irkucku.JPG",
    alt: "The Irkutsk Drama Theatre, a historic landmark building in Irkutsk, Russia",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Teatr_Dramatyczny_w_Irkucku.JPG",
  },
  "russia::izhevsk": {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Saint_Michael_the_Archangel_Church_%28Izhevsk%29-52.jpg/1280px-Saint_Michael_the_Archangel_Church_%28Izhevsk%29-52.jpg",
    alt: "Aerial view of Izhevsk, Russia with the Cathedral of St. Michael the Archangel and the Izhevsk Pond",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Saint_Michael_the_Archangel_Church_(Izhevsk)-52.jpg",
  },
  "russia::kaluga": {
    url: "https://upload.wikimedia.org/wikipedia/commons/4/48/%D0%9A%D0%B0%D0%BB%D1%83%D0%B3%D0%B0._%D0%9F%D1%80%D0%B8%D1%81%D1%83%D1%82%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D0%B5_%D0%BC%D0%B5%D1%81%D1%82%D0%B0.jpg",
    alt: "The historic Gostiny Dvor trading arcade (Prisutstvennye Mesta) in Kaluga, Russia",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:%D0%9A%D0%B0%D0%BB%D1%83%D0%B3%D0%B0._%D0%9F%D1%80%D0%B8%D1%81%D1%83%D1%82%D1%81%D1%82%D0%B2%D0%B5%D0%BD%D0%BD%D1%8B%D0%B5_%D0%BC%D0%B5%D1%81%D1%82%D0%B0.jpg",
  },
  "russia::kemerovo": {
    url: "https://upload.wikimedia.org/wikipedia/commons/2/25/Kemerovo1.jpg",
    alt: "Elevated view of the Kemerovo, Russia cityscape at dusk",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Kemerovo1.jpg",
  },
  "russia::khabarovsk": {
    url: "https://upload.wikimedia.org/wikipedia/commons/e/e4/%D0%A3%D1%81%D1%81%D1%83%D1%80%D0%B8%D0%B9%D1%81%D0%BA%D0%B8%D0%B9_%D0%B1%D1%83%D0%BB%D1%8C%D0%B2%D0%B0%D1%80.jpg",
    alt: "Aerial view of Ussuriysky Boulevard and the Khabarovsk, Russia skyline",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:%D0%A3%D1%81%D1%81%D1%83%D1%80%D0%B8%D0%B9%D1%81%D0%BA%D0%B8%D0%B9_%D0%B1%D1%83%D0%BB%D1%8C%D0%B2%D0%B0%D1%80.jpg",
  },
  "russia::khanty-mansiysk": {
    url: "https://upload.wikimedia.org/wikipedia/commons/f/fc/%D0%A5%D0%B0%D0%BD%D1%82%D1%8B-%D0%9C%D0%B0%D0%BD%D1%81%D0%B8%D0%B9%D1%81%D0%BA%2C_%D1%81%D0%BE%D0%B1%D0%BE%D1%80_%D0%92%D0%BE%D1%81%D0%BA%D1%80%D0%B5%D1%81%D0%B5%D0%BD%D0%B8%D1%8F_%D0%A5%D1%80%D0%B8%D1%81%D1%82%D0%BE%D0%B2%D0%B0.jpg",
    alt: "The Cathedral of the Resurrection of Christ in Khanty-Mansiysk, Russia, in winter",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:%D0%A5%D0%B0%D0%BD%D1%82%D1%8B-%D0%9C%D0%B0%D0%BD%D1%81%D0%B8%D0%B9%D1%81%D0%BA,_%D1%81%D0%BE%D0%B1%D0%BE%D1%80_%D0%92%D0%BE%D1%81%D0%BA%D1%80%D0%B5%D1%81%D0%B5%D0%BD%D0%B8%D1%8F_%D0%A5%D1%80%D0%B8%D1%81%D1%82%D0%BE%D0%B2%D0%B0.jpg",
  },
  "russia::maykop": {
    url: "https://upload.wikimedia.org/wikipedia/commons/b/b6/CLOUDS_VIEW_%282011-07-22_18-42-09%29_-_panoramio.jpg",
    alt: "Residential skyline of Maykop, Russia at dusk",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:CLOUDS_VIEW_(2011-07-22_18-42-09)_-_panoramio.jpg",
  },
  "russia::moscow": {
    url: "https://upload.wikimedia.org/wikipedia/commons/8/85/Saint_Basil%27s_Cathedral_and_the_Red_Square.jpg",
    alt: "Saint Basil's Cathedral and Red Square in Moscow, Russia",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Saint_Basil%27s_Cathedral_and_the_Red_Square.jpg",
  },
  "russia::mytishchi": {
    url: "https://upload.wikimedia.org/wikipedia/commons/c/cc/%D0%9C%D1%8B%D1%82%D0%B8%D1%89%D0%B8_%28%D0%A6%D0%B5%D1%80%D0%BA%D0%BE%D0%B2%D1%8C_%D0%91%D0%BB%D0%B0%D0%B3%D0%BE%D0%B2%D0%B5%D1%89%D0%B5%D0%BD%D0%B8%D1%8F%29-55.jpg",
    alt: "Aerial view of the Annunciation Church and the Mytishchi, Russia skyline at sunset",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:%D0%9C%D1%8B%D1%82%D0%B8%D1%89%D0%B8_(%D0%A6%D0%B5%D1%80%D0%BA%D0%BE%D0%B2%D1%8C_%D0%91%D0%BB%D0%B0%D0%B3%D0%BE%D0%B2%D0%B5%D1%89%D0%B5%D0%BD%D0%B8%D1%8F)-55.jpg",
  },
  "russia::nizhny novgorod": {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Nizhny_Novgorod_2025-04-29_Minin_and_Pozharsky_square_01.jpg/1280px-Nizhny_Novgorod_2025-04-29_Minin_and_Pozharsky_square_01.jpg",
    alt: "The Dmitrievskaya Tower of the Nizhny Novgorod Kremlin at Minin and Pozharsky Square, Russia",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Nizhny_Novgorod_2025-04-29_Minin_and_Pozharsky_square_01.jpg",
  },
  "russia::novosibirsk": {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Opera-and-Ballet-theatre-Novosibirsk.jpg/1280px-Opera-and-Ballet-theatre-Novosibirsk.jpg",
    alt: "The Novosibirsk Opera and Ballet Theatre illuminated at night, an iconic landmark of Novosibirsk, Russia",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Opera-and-Ballet-theatre-Novosibirsk.jpg",
  },
  "russia::omsk": {
    url: "https://upload.wikimedia.org/wikipedia/commons/c/c8/Omsk_Collage_2016.png",
    alt: "Photo montage of landmarks in Omsk, Russia, including the Drama Theatre and the Irtysh river bridge",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Omsk_Collage_2016.png",
  },
  "russia::orel": {
    url: "https://upload.wikimedia.org/wikipedia/commons/e/e9/%D0%9E%D1%80%D1%91%D0%BB%2C_%D0%BF%D0%BB%D0%BE%D1%89%D0%B0%D0%B4%D1%8C_%D0%9A._%D0%9C%D0%B0%D1%80%D0%BA%D1%81%D0%B0%2C_2_%283%29.jpg",
    alt: "Historic building on Karl Marx Square in Oryol (Orel), Russia",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:%D0%9E%D1%80%D1%91%D0%BB,_%D0%BF%D0%BB%D0%BE%D1%89%D0%B0%D0%B4%D1%8C_%D0%9A._%D0%9C%D0%B0%D1%80%D0%BA%D1%81%D0%B0,_2_(3).jpg",
  },
  "russia::penza": {
    url: "https://upload.wikimedia.org/wikipedia/commons/b/bd/View_of_the_Church_of_the_Merciful_Saviour%2C_Penza.jpg",
    alt: "Aerial view of the Church of the Merciful Saviour and the Penza, Russia skyline",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:View_of_the_Church_of_the_Merciful_Saviour,_Penza.jpg",
  },
  "russia::perm": {
    url: "https://upload.wikimedia.org/wikipedia/commons/c/c7/Kama_River._Perm._Art_Gallery_%28former_Transfiguration_Cathedral%29_P6242387_2575.jpg",
    alt: "The Transfiguration Cathedral (Perm Art Gallery) on the banks of the Kama River in Perm, Russia",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Kama_River._Perm._Art_Gallery_(former_Transfiguration_Cathedral)_P6242387_2575.jpg",
  },
  "russia::petrozavodsk": {
    url: "https://upload.wikimedia.org/wikipedia/commons/a/af/Petrozavodsk_Collage_2020.png",
    alt: "Photo montage of landmarks in Petrozavodsk, Russia, including the Peter the Great monument and the Lake Onega waterfront",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Petrozavodsk_Collage_2020.png",
  },
  "russia::samara": {
    url: "https://upload.wikimedia.org/wikipedia/commons/8/8e/%D0%9C%D0%BE%D0%BD%D1%83%D0%BC%D0%B5%D0%BD%D1%82_%D0%A1%D0%BB%D0%B0%D0%B2%D1%8B_%D0%A1%D0%B0%D0%BC%D0%B0%D1%80%D0%B0.jpg",
    alt: "The Monument of Glory overlooking the skyline of Samara, Russia at dusk",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:%D0%9C%D0%BE%D0%BD%D1%83%D0%BC%D0%B5%D0%BD%D1%82_%D0%A1%D0%BB%D0%B0%D0%B2%D1%8B_%D0%A1%D0%B0%D0%BC%D0%B0%D1%80%D0%B0.jpg",
  },
  "russia::st. petersburg": {
    url: "https://upload.wikimedia.org/wikipedia/commons/7/7a/Auf_der_Neva_in_St._Petersburg%2C_Russland_2H1A3080WI.jpg",
    alt: "The Peter and Paul Fortress on the Neva River in St. Petersburg, Russia, with a tall ship",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Auf_der_Neva_in_St._Petersburg,_Russland_2H1A3080WI.jpg",
  },
  "russia::stavropol": {
    url: "https://upload.wikimedia.org/wikipedia/commons/c/cf/%D0%A1%D1%82%D0%B0%D0%B2%D1%80%D0%BE%D0%BF%D0%BE%D0%BB%D1%8C_2020.jpg",
    alt: "A modern pedestrian street in central Stavropol, Russia",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:%D0%A1%D1%82%D0%B0%D0%B2%D1%80%D0%BE%D0%BF%D0%BE%D0%BB%D1%8C_2020.jpg",
  },
  "russia::ufa": {
    url: "https://upload.wikimedia.org/wikipedia/commons/4/45/Ufa_view_from_Belaya_river_2022-05.jpg",
    alt: "The Ufa, Russia skyline viewed from the Belaya River",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ufa_view_from_Belaya_river_2022-05.jpg",
  },
  "russia::veliky novgorod": {
    url: "https://upload.wikimedia.org/wikipedia/commons/8/86/Veliky_Novgorod_montage_%282015%29.png",
    alt: "Photo montage of landmarks in Veliky Novgorod, Russia, including the Novgorod Kremlin and Millennium of Russia monument",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Veliky_Novgorod_montage_(2015).png",
  },
  "russia::vladivostok": {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Zolotoy_Bridge_evening_panorama_%2822099283131%29.jpg/1280px-Zolotoy_Bridge_evening_panorama_%2822099283131%29.jpg",
    alt: "The Zolotoy (Golden) Bridge over the Golden Horn Bay in Vladivostok, Russia, at night",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Zolotoy_Bridge_evening_panorama_(22099283131).jpg",
  },
  "russia::volgograd": {
    url: "https://upload.wikimedia.org/wikipedia/commons/8/88/Volgograd_Montage_2016.png",
    alt: "Photo montage of landmarks in Volgograd, Russia, including the Motherland Calls statue and the Grain Elevator memorial",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Volgograd_Montage_2016.png",
  },
  "russia::voronezh": {
    url: "https://upload.wikimedia.org/wikipedia/commons/9/91/%D0%93%D0%BB%D0%B0%D0%B2%D0%BD%D0%BE%D0%B5_%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_%D1%83%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F_%D0%AE%D0%92%D0%96%D0%94.jpg",
    alt: "Aerial dusk view of the Voronezh, Russia skyline",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:%D0%93%D0%BB%D0%B0%D0%B2%D0%BD%D0%BE%D0%B5_%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_%D1%83%D0%BF%D1%80%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F_%D0%AE%D0%92%D0%96%D0%94.jpg",
  },
  "russia::yakutsk": {
    url: "https://upload.wikimedia.org/wikipedia/commons/4/42/%D0%92%D0%B8%D0%B4_%D0%BD%D0%B0_%D0%B3%D0%BE%D1%80%D0%BE%D0%B4_%D1%81_%D0%B2%D1%8B%D1%81%D0%BE%D1%82%D1%8B%2C_%D0%AF%D0%BA%D1%83%D1%82%D1%81%D0%BA_19.06.2026.jpg",
    alt: "Aerial view of Yakutsk, Russia",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Вид_на_город_с_высоты,_Якутск_19.06.2026.jpg",
  },
  "russia::yekaterinburg": {
    url: "https://upload.wikimedia.org/wikipedia/commons/e/e9/Yekaterinburg_skyline.JPG",
    alt: "Skyline of Yekaterinburg, Russia",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Yekaterinburg_skyline.JPG",
  },
  "serbia::kragujevac": {
    url: "https://upload.wikimedia.org/wikipedia/commons/d/dc/Kragujevac_001.jpg",
    alt: "Cityscape of Kragujevac, Serbia",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Kragujevac_001.jpg",
  },
  "sweden::gothenburg": {
    url: "https://upload.wikimedia.org/wikipedia/commons/a/ac/Gothenburg_skyline_%283883926931%29.jpg",
    alt: "Skyline of Gothenburg, Sweden",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Gothenburg_skyline_(3883926931).jpg",
  },
  "switzerland::geneva": {
    url: "https://upload.wikimedia.org/wikipedia/commons/8/8e/Jet_d%27Eau_Fountain_Geneva.jpg",
    alt: "Jet d'Eau fountain landmark in Geneva, Switzerland",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Jet_d'Eau_Fountain_Geneva.jpg",
  },
  "trinidad-and-tobago::st. augustine": {
    url: "https://upload.wikimedia.org/wikipedia/commons/8/8f/TnT_St._Augustine_UWI_CampusFXD.jpg",
    alt: "University of the West Indies campus grounds in St. Augustine, Trinidad and Tobago",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:TnT_St._Augustine_UWI_CampusFXD.jpg",
  },
  "uganda::mbarara": {
    url: "https://upload.wikimedia.org/wikipedia/commons/8/88/High_Street_in_Mbarara_City_01.jpg",
    alt: "High Street in Mbarara city, Uganda",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:High_Street_in_Mbarara_City_01.jpg",
  },
  "united-arab-emirates::abu dhabi": {
    url: "https://upload.wikimedia.org/wikipedia/commons/9/9c/Abu_dhabi_skylines_2014.jpg",
    alt: "Skyline of Abu Dhabi, United Arab Emirates",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Abu_dhabi_skylines_2014.jpg",
  },
  "united-arab-emirates::ajman": {
    url: "https://upload.wikimedia.org/wikipedia/commons/9/95/Ajman_Aerial_2009.jpg",
    alt: "Aerial view of Ajman, United Arab Emirates",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Ajman_Aerial_2009.jpg",
  },
  "united-kingdom::huddersfield, west yorkshire": {
    url: "https://upload.wikimedia.org/wikipedia/commons/6/69/Huddersfield_station_facade.jpg",
    alt: "Huddersfield railway station facade, West Yorkshire, England",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Huddersfield_station_facade.jpg",
  },
  "united-kingdom::oxford": {
    url: "https://upload.wikimedia.org/wikipedia/commons/a/aa/Oxford_skyline.jpg",
    alt: "Skyline of Oxford, England, with its historic spires",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Oxford_skyline.jpg",
  },
  "united-states::amherst, massachusetts": {
    url: "https://upload.wikimedia.org/wikipedia/commons/1/1d/Town_Hall_%28Amherst%2C_Massachusetts%29_-_IMG_6526.JPG",
    alt: "Town Hall in Amherst, Massachusetts",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Town_Hall_(Amherst,_Massachusetts)_-_IMG_6526.JPG",
  },
  "united-states::newark": {
    url: "https://upload.wikimedia.org/wikipedia/commons/6/6e/Panorama_of_Newark_NJ_Feb_5_2006.jpg",
    alt: "Panoramic skyline view of Newark, New Jersey",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Panorama_of_Newark_NJ_Feb_5_2006.jpg",
  },
  "united-states::pasadena": {
    url: "https://upload.wikimedia.org/wikipedia/commons/d/d3/Pasadena_City_Hall_DSC_4681_ad.JPG",
    alt: "Pasadena City Hall, California",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Pasadena_City_Hall_DSC_4681_ad.JPG",
  },
  "uzbekistan::angren": {
    url: "https://upload.wikimedia.org/wikipedia/commons/f/f8/%D0%9F%D0%B0%D1%80%D0%BA_%D0%B2_%D0%B3%D0%BE%D1%80%D0%BE%D0%B4%D0%B5_%D0%90%D0%BD%D0%B3%D1%80%D0%B5%D0%BD.jpg",
    alt: "City park in Angren, Uzbekistan",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Парк_в_городе_Ангрен.jpg",
  },
  "uzbekistan::bukhara": {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Po-i-Kalyan_in_Bukhara.jpg/1280px-Po-i-Kalyan_in_Bukhara.jpg",
    alt: "Po-i-Kalyan complex, an iconic landmark of Bukhara, Uzbekistan",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Po-i-Kalyan_in_Bukhara.jpg",
  },
  "uzbekistan::chirchik": {
    url: "https://upload.wikimedia.org/wikipedia/commons/8/89/%D0%A7%D0%B8%D1%80%D1%87%D0%B8%D0%BA_-_panoramio_%281%29.jpg",
    alt: "Panoramic view of Chirchik, Uzbekistan",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Чирчик_-_panoramio_(1).jpg",
  },
  "uzbekistan::fergana": {
    url: "https://upload.wikimedia.org/wikipedia/commons/4/4c/%D0%A4%D0%B5%D1%80%D0%B3%D0%B0%D0%BD%D0%B0_%D0%B0%D0%BB%D0%BB%D0%B5%D1%8F.jpg",
    alt: "Tree-lined downtown avenue in Fergana, Uzbekistan",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Фергана_аллея.jpg",
  },
  "uzbekistan::gulistan": {
    url: "https://upload.wikimedia.org/wikipedia/commons/a/a7/%D0%93%D0%BE%D1%80%D0%BE%D0%B4_%D0%93%D1%83%D0%BB%D0%B8%D1%81%D1%82%D0%B0%D0%BD.jpg",
    alt: "Cityscape of Gulistan, Uzbekistan",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Город_Гулистан.jpg",
  },
  "uzbekistan::navoi": {
    url: "https://upload.wikimedia.org/wikipedia/commons/d/d3/%D0%93%D0%BE%D1%80%D0%BE%D0%B4_%D0%9D%D0%B0%D0%B2%D0%BE%D0%B8%2C_%D0%BF%D1%80%D0%BE%D1%81%D0%BF%D0%B5%D0%BA%D1%82_%D0%A5%D0%B0%D0%BB%D0%BA%D0%BB%D0%B0%D1%80_%D0%94%D1%83%D1%81%D1%82%D0%BB%D0%B8%D0%B3%D0%B8.JPG",
    alt: "Main avenue (Khalklar Dustligi) in Navoi, Uzbekistan",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Город_Навои,_проспект_Халклар_Дустлиги.JPG",
  },
  "uzbekistan::nukus": {
    url: "https://upload.wikimedia.org/wikipedia/commons/d/df/Nukus.jpg",
    alt: "City center of Nukus, Uzbekistan",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Nukus.jpg",
  },
  "uzbekistan::tashkent": {
    url: "https://upload.wikimedia.org/wikipedia/commons/3/33/Tashkent_skyline_2019.jpg",
    alt: "Skyline of Tashkent, Uzbekistan",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Tashkent_skyline_2019.jpg",
  },
  "uzbekistan::urgench": {
    url: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Street_in_Urgench_with_clocktower.jpg/1280px-Street_in_Urgench_with_clocktower.jpg",
    alt: "Street with clocktower in Urgench, Uzbekistan",
    sourceLabel: "Wikimedia Commons",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Street_in_Urgench_with_clocktower.jpg",
  },
};

function normalize(value: string) {
  return value.trim().toLowerCase();
}

export function getCityMedia(countrySlug: string, city: string) {
  return cityMediaMap[`${normalize(countrySlug)}::${normalize(city)}`] ?? null;
}

export function getCountryMedia(countrySlug: string) {
  return getCountryHeroImage(countrySlug);
}
