import { useState } from "react";
import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import { colors } from "../../theme/tokens";
import type { GuideFilterKey, GuideFilterOptions, GuideFilters } from "../../types/domain";
export const EMPTY_GUIDE_FILTERS: GuideFilters = { country: "", university: "", course: "", year: "", state: "", language: "" };
const ALL_LABELS: Record<GuideFilterKey, string> = { country: "All countries", university: "All universities", course: "All programs", year: "All years / batches", state: "All home states", language: "All languages" };
const LABELS: Record<GuideFilterKey, string> = { country: "Country", university: "University", course: "Program", year: "Year / batch", state: "Home state", language: "Language" };
export function GuideFiltersSheet({ initial, options, onClose, onApply }: { initial: GuideFilters; options?: GuideFilterOptions; onClose: () => void; onApply: (filters: GuideFilters) => void }) {
  const [draft, setDraft] = useState(initial);
  const [expanded, setExpanded] = useState<GuideFilterKey | null>("country");
  const selectedCount = Object.values(draft).filter(Boolean).length;
  return <Modal visible animationType="slide" presentationStyle="pageSheet" onRequestClose={onClose}><SafeAreaView style={s.root} edges={["top", "bottom"]}><View style={s.header}><Text style={s.title}>Filter student guides</Text><Pressable accessibilityRole="button" accessibilityLabel="Close filters" onPress={onClose} style={s.close}><Ionicons name="close" size={23} color={colors.ink} /></Pressable></View><ScrollView contentContainerStyle={s.content}>{(Object.keys(LABELS) as GuideFilterKey[]).map(key => <View key={key} style={s.group}><Pressable accessibilityRole="button" accessibilityState={{ expanded: expanded === key }} onPress={() => setExpanded(expanded === key ? null : key)} style={s.groupHeader}><View style={s.flex}><Text style={s.label}>{LABELS[key]}</Text><Text style={s.value}>{options?.[key]?.find(o => o.value === draft[key])?.label ?? "All"}</Text></View><Ionicons name={expanded === key ? "chevron-up" : "chevron-down"} size={18} color={colors.muted} /></Pressable>{expanded === key ? <View style={s.choices}>{[{ value: "", label: ALL_LABELS[key] }, ...(options?.[key] ?? [])].map(option => <Pressable accessibilityRole="radio" accessibilityState={{ checked: draft[key] === option.value }} key={option.value} onPress={() => setDraft(current => ({ ...current, [key]: option.value, ...(key === "country" ? { university: "" } : {}) }))} style={[s.choice, draft[key] === option.value && s.selected]}><Text style={[s.choiceText, draft[key] === option.value && s.selectedText]}>{option.label}</Text>{draft[key] === option.value ? <Ionicons name="checkmark" size={15} color="#fff" /> : null}</Pressable>)}</View> : null}</View>)}</ScrollView><View style={s.footer}><Pressable accessibilityRole="button" onPress={() => setDraft({ ...EMPTY_GUIDE_FILTERS })} style={s.reset}><Text style={s.resetText}>Clear all</Text></Pressable><Pressable accessibilityRole="button" onPress={() => onApply(draft)} style={s.apply}><Text style={s.applyText}>Show guides{selectedCount ? ` · ${selectedCount} ${selectedCount === 1 ? "filter" : "filters"}` : ""}</Text></Pressable></View></SafeAreaView></Modal>;
}
const s = StyleSheet.create({ root: { flex: 1, backgroundColor: "#fff" }, header: { padding: 20, paddingBottom: 10, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, title: { fontFamily: "Fraunces-SemiBold", fontSize: 24, color: colors.ink }, close: { width: 44, height: 44, alignItems: "center", justifyContent: "center" }, content: { paddingHorizontal: 22, paddingBottom: 24 }, group: { borderBottomWidth: 1, borderColor: colors.line, paddingVertical: 8 }, groupHeader: { flexDirection: "row", alignItems: "center", paddingVertical: 10, gap: 12 }, flex: { flex: 1 }, label: { fontFamily: "PlusJakartaSans-SemiBold", fontSize: 13, color: colors.ink }, value: { fontFamily: "PlusJakartaSans-Regular", fontSize: 12, color: colors.muted, marginTop: 5 }, choices: { flexDirection: "row", flexWrap: "wrap", gap: 8, paddingVertical: 10 }, choice: { flexDirection: "row", alignItems: "center", gap: 6, minHeight: 44, paddingHorizontal: 12, paddingVertical: 9, borderRadius: 10, borderWidth: 1, borderColor: colors.line, maxWidth: "100%" }, selected: { backgroundColor: colors.primary, borderColor: colors.primary }, choiceText: { fontFamily: "PlusJakartaSans-Medium", fontSize: 12, color: colors.ink, flexShrink: 1 }, selectedText: { color: "#fff" }, footer: { padding: 20, borderTopWidth: 1, borderColor: colors.line, flexDirection: "row", gap: 15, alignItems: "center" }, reset: { minHeight: 48, paddingHorizontal: 12, justifyContent: "center" }, resetText: { fontFamily: "PlusJakartaSans-SemiBold", fontSize: 12, color: colors.muted }, apply: { flex: 1, minHeight: 48, padding: 14, alignItems: "center", justifyContent: "center", borderRadius: 12, backgroundColor: colors.accent }, applyText: { fontFamily: "PlusJakartaSans-SemiBold", fontSize: 12, color: "#fff" } });
